CREATE TABLE ALUMNOS(
 cCodAlu VARCHAR2(6) CONSTRAINT PK_ALUMNOS PRIMARY KEY,
 cNomAlu VARCHAR2(100) NOT NULL
);
CREATE TABLE CURSOS(
 cCodCurso VARCHAR2(6) CONSTRAINT PK_CURSOS PRIMARY KEY,
 cNomCurso VARCHAR2(100) NOT NULL,
 nNumExa NUMBER(3) DEFAULT 1 NOT NULL
);
CREATE TABLE MATRICULAS(
 cCodAlu VARCHAR2(6) NOT NULL,
 cCodCurso VARCHAR2(6) NOT NULL,
 nNotaMedia NUMBER(3) DEFAULT 0 NOT NULL,
 CONSTRAINT PK_MATRICULAS PRIMARY KEY (cCodAlu,cCodCurso)
);
ALTER TABLE MATRICULAS ADD CONSTRAINT FK_MATRICULAS_ALUMNO FOREIGN KEY (cCodAlu) REFERENCES ALUMNOS(cCodAlu);
ALTER TABLE MATRICULAS ADD CONSTRAINT FK_MATRICULAS_CURSOS FOREIGN KEY (cCodCurso)
REFERENCES CURSOS(cCodCurso);
CREATE TABLE EXAMENES(
 cCodAlu VARCHAR2(6) NOT NULL,
 cCodCurso VARCHAR2(6) NOT NULL,
 nNumExam NUMBER(3) DEFAULT 1 NOT NULL,
 dFecExam DATE,
 nNotaExam NUMBER(6,2) DEFAULT 0 NOT NULL,
 CONSTRAINT PK_EXAMENES PRIMARY KEY (cCodAlu,cCodCurso,nNumExam)
);
ALTER TABLE EXAMENES ADD CONSTRAINT FK_EXAMENES_MATR FOREIGN KEY (cCodAlu,cCodCurso)
REFERENCES MATRICULAS(cCodAlu,cCodCurso);


INSERT INTO ALUMNOS VALUES ('001','Antonio');
INSERT INTO ALUMNOS VALUES ('002','Maria');
INSERT INTO CURSOS VALUES ('I001','Ingles Basico',5);
INSERT INTO CURSOS VALUES ('I002','Ingles Intermedio',8);
INSERT INTO CURSOS VALUES ('I003','Ingles Avanzado',10);
INSERT INTO CURSOS VALUES ('F001','Frances Basico',3);
INSERT INTO CURSOS VALUES ('C002','Chino Intermedio',9);
COMMIT;


CREATE OR REPLACE PROCEDURE sp_AltaMatricula (xcCodAlu VARCHAR2, xcCodCurso VARCHAR2, xError OUT
NUMBER)
IS 

xNR NUMBER;
BEGIN
    
    INSERT INTO MATRICULAS VALUES(xcCodAlu,xcCodCurso,0);
    
    SELECT NNUMEXA INTO xNR FROM CURSOS WHERE CCODCURSO = xcCodCurso;
    
    FOR I IN 1..xNR LOOP
        INSERT INTO EXAMENES VALUES(xcCodAlu,xcCodCurso,I,SYSDATE,0);
        COMMIT;
    END LOOP;
    xError := 0;
EXCEPTION WHEN OTHERS 
THEN xError := -1;
END;


CREATE OR REPLACE TRIGGER tr_Examenes_Upd
AFTER UPDATE
ON EXAMENES
FOR EACH ROW
DECLARE
    xNumeroExam NUMBER;
    xNotaMedia NUMBER;

BEGIN
    -- Obtener el número de exámenes y la nota media actual del estudiante en el curso
    SELECT NNOTAMEDIA INTO xNotaMedia FROM MATRICULAS WHERE MATRICULAS.CCODALU = :OLD.CCODALU AND MATRICULAS.CCODCURSO = :OLD.CCODCURSO;
    SELECT NNUMEXA INTO xNumeroExam FROM CURSOS WHERE CURSOS.CCODCURSO = :OLD.CCODCURSO;

    -- Calcular la nueva nota media
    xNotaMedia := xNotaMedia - (:OLD.NNOTAEXAM / xNumeroExam); -- Resta la nota antigua
    xNotaMedia := xNotaMedia + (:NEW.NNOTAEXAM / xNumeroExam); -- Agrega la nueva nota

    -- Actualizar la nota media en la tabla MATRICULAS
    UPDATE MATRICULAS SET NNOTAMEDIA = xNotaMedia
    WHERE MATRICULAS.CCODALU = :OLD.CCODALU AND MATRICULAS.CCODCURSO = :OLD.CCODCURSO;
    
END;




